# Generated by Django 4.0.2 on 2023-01-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
